const P=window.ESENTIA_PRODUCTS, CFG=window.ESENTIA_CONFIG;
let filter={catalog:'Todos',gender:'Todos',q:'',sort:'default',favorites:false}, shown=48, current=null, modalQty=1;
let cart=JSON.parse(localStorage.getItem('esentia_cart')||'{}'); let fav=new Set(JSON.parse(localStorage.getItem('esentia_fav')||'[]'));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>`${CFG.currency}${Math.round(n).toLocaleString('es-HN')}`;
function discTier(q){return q>=6?.15:q>=4?.10:q>=3?.08:q>=2?.05:0}
function pricing(p,totalUnits){totalUnits=Math.max(1,totalUnits);const tier=discTier(totalUnits), freight=CFG.freightPerOrder/totalUnits; const max=Math.max(0,(p.detail-(p.wholesale+freight+CFG.minimumProfitPerUnit))/p.detail); const rate=Math.min(tier,max); const unit=Math.round(p.detail*(1-rate)); return {tier,rate,unit,saving:p.detail-unit,max};}
function imgSrc(p){return window.ESENTIA_IMAGES[p.id]||""}
function filtered(){let a=P.filter(p=>p.available!==false&&(filter.catalog==='Todos'||p.catalog===filter.catalog)&&(filter.gender==='Todos'||p.gender===filter.gender));if(filter.q){const q=filter.q.toLowerCase();a=a.filter(p=>(p.name+' '+p.presentation+' '+p.catalog+' '+p.gender).toLowerCase().includes(q))}if(filter.favorites)a=a.filter(p=>fav.has(p.id));if(filter.sort==='name')a.sort((a,b)=>a.name.localeCompare(b.name));if(filter.sort==='low')a.sort((a,b)=>a.detail-b.detail);if(filter.sort==='high')a.sort((a,b)=>b.detail-a.detail);return a}
function card(p){return `<article class="card"><button class="heart ${fav.has(p.id)?'on':''}" data-fav="${p.id}">${fav.has(p.id)?'♥':'♡'}</button><div class="prodimg" data-open="${p.id}"><img src="${imgSrc(p)}" alt="${p.name}" loading="lazy"></div><div class="cardbody"><span class="tag">${p.catalog}</span><h3 data-open="${p.id}">${p.name}</h3><div class="meta">${p.presentation||p.gender} · ${p.gender}</div><div class="price">${money(p.detail)}</div><div class="savehint">Hasta 15% por volumen*</div><button class="add" data-add="${p.id}">Agregar al carrito</button></div></article>`}
function render(){const a=filtered();$('#count').textContent=`${a.length.toLocaleString('es-HN')} productos`;$('#grid').innerHTML=a.slice(0,shown).map(card).join('')||'<div class="empty">No encontramos productos con esos filtros.</div>';$('#more').style.display=shown<a.length?'block':'none';bindGrid()}
function bindGrid(){ $$('[data-open]').forEach(x=>x.onclick=()=>openProduct(+x.dataset.open)); $$('[data-add]').forEach(x=>x.onclick=()=>add(+x.dataset.add,1)); $$('[data-fav]').forEach(x=>x.onclick=e=>{e.stopPropagation();toggleFav(+x.dataset.fav)}) }
function toggleFav(id){fav.has(id)?fav.delete(id):fav.add(id);localStorage.setItem('esentia_fav',JSON.stringify([...fav]));render()}
function tiers(p){return [1,2,3,4,6].map(q=>{let x=pricing(p,q);return `<div class="tier"><b>${q===4?'4–5':q===6?'6+':q} ${q===1?'unidad':'unidades'}</b><span class="pct">${Math.round(x.rate*100)}%</span><span>${money(x.unit)} c/u</span><span class="sav">${x.saving?`Ahorra ${money(x.saving*q)}`:'Precio normal'}</span></div>`}).join('')}
function openProduct(id){current=P.find(p=>p.id===id);modalQty=1;refreshModal();show('modal')}
function refreshModal(){const p=current,x=pricing(p,modalQty);$('#modalContent').innerHTML=`<div class="modalgrid"><div class="modalimgwrap"><div class="modalimg"><img src="${imgSrc(p)}" alt="${p.name}"></div></div><div class="modaldetail"><span class="tag">${p.catalog}</span><h2>${p.name}</h2><div class="meta">${p.presentation||'Presentación según catálogo'} · ${p.gender}</div><div style="display:flex;align-items:center;justify-content:space-between;gap:10px"><div class="price">${money(p.detail)}</div><span class="stock">Por encargo</span></div><div class="tierbox"><div class="tierhead">◆ Lleva más y ahorra</div>${tiers(p)}</div><div class="qtyrow"><div class="qty"><button id="qminus">−</button><span>${modalQty}</span><button id="qplus">+</button></div><div class="calc"><div>Precio por unidad: <b>${money(x.unit)}</b></div><div class="big">Total: ${money(x.unit*modalQty)}</div><div class="green">${x.saving?`Ahorras ${money(x.saving*modalQty)}`:'Precio normal'}</div></div></div><button class="modaladd" id="modalAdd">🛒 Agregar al carrito</button><div class="note">*El descuento se aplica hasta donde permita conservar el margen mínimo del producto.</div></div></div>`;$('#qminus').onclick=()=>{modalQty=Math.max(1,modalQty-1);refreshModal()};$('#qplus').onclick=()=>{modalQty++;refreshModal()};$('#modalAdd').onclick=()=>{add(p.id,modalQty);hideAll();openCart()}}
function add(id,q){cart[id]=(cart[id]||0)+q;saveCart();updateBadge()}
function saveCart(){localStorage.setItem('esentia_cart',JSON.stringify(cart))}
function totalUnits(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function updateBadge(){const n=totalUnits();$('#cartBadge').textContent=n;$('#cartBadge').style.display=n?'grid':'none'}
function cartLines(){const total=totalUnits();return Object.entries(cart).map(([id,q])=>{const p=P.find(x=>x.id===+id),x=pricing(p,total);return {p,q,x,line:x.unit*q,normal:p.detail*q}})}
function renderCart(){const lines=cartLines(),units=totalUnits();$('#cartSub').textContent=`${units} ${units===1?'producto':'productos'}`;const next=units<2?2:units<3?3:units<4?4:units<6?6:null;const tier=discTier(units);const promo=units===0?'Combina perfumes diferentes y ahorra más.':next?`Agrega ${next-units} producto${next-units===1?'':'s'} más y desbloquea ${Math.round(discTier(next)*100)}% de descuento.`:`¡Descuento máximo desbloqueado: ${Math.round(tier*100)}%!`;$('#cartBody').innerHTML=`<div class="cartpromo"><b>${promo}</b><small>Cuenta el total de unidades, aunque sean perfumes diferentes.</small></div>`+(lines.length?lines.map(({p,q,x,line})=>`<div class="cartitem"><div class="thumb"><img src="${imgSrc(p)}" alt="${p.name}"></div><div class="ci"><h4>${p.name}</h4><div class="line">${money(x.unit)} c/u · descuento ${Math.round(x.rate*100)}%</div><b>${money(line)}</b><br><button class="remove" data-rm="${p.id}">Eliminar</button></div><div class="stepper"><button data-dec="${p.id}">−</button><b>${q}</b><button data-inc="${p.id}">+</button></div></div>`).join(''):'<div class="empty">Su carrito está vacío.</div>');let normal=lines.reduce((s,l)=>s+l.normal,0),total=lines.reduce((s,l)=>s+l.line,0),save=normal-total;$('#summary').innerHTML=`<div class="sumrow"><span>Precio normal</span><b>${money(normal)}</b></div><div class="sumrow"><span>Ahorro</span><b style="color:#14854a">−${money(save)}</b></div><div class="sumrow total"><span>Total a pagar</span><b>${money(total)}</b></div><button class="whatsapp" id="sendWA" ${!lines.length?'disabled':''}>◉ Encargar por WhatsApp</button><div class="note">Usted solo confirma y envía. No se realiza ningún cobro dentro del catálogo.</div>`;$$('[data-dec]').forEach(x=>x.onclick=()=>chg(+x.dataset.dec,-1));$$('[data-inc]').forEach(x=>x.onclick=()=>chg(+x.dataset.inc,1));$$('[data-rm]').forEach(x=>x.onclick=()=>{delete cart[x.dataset.rm];saveCart();updateBadge();renderCart()});if(lines.length)$('#sendWA').onclick=sendWA}
function chg(id,d){cart[id]=Math.max(0,(cart[id]||0)+d);if(!cart[id])delete cart[id];saveCart();updateBadge();renderCart()}
function sendWA(){const lines=cartLines(),normal=lines.reduce((s,l)=>s+l.normal,0),total=lines.reduce((s,l)=>s+l.line,0);let msg='¡Hola! Quiero encargar los siguientes perfumes de ESENTIA:\n\n';lines.forEach((l,i)=>{msg+=`${i+1}. ${l.p.name}\nCantidad: ${l.q}\nPrecio unitario: ${money(l.x.unit)}\nSubtotal: ${money(l.line)}\n\n`});msg+=`Total del pedido: ${money(total)}\nAhorro: ${money(normal-total)}\n\nQuedo atento(a) a la confirmación de disponibilidad y entrega. ¡Gracias!`;const num=(CFG.whatsapp||'').replace(/\D/g,'');window.open(`https://wa.me/${num}?text=${encodeURIComponent(msg)}`,'_blank')}
function show(which){$('#overlay').classList.add('show');$('#'+which).classList.add('show')}
function hideAll(){$('#overlay').classList.remove('show');$('#modal').classList.remove('show');$('#drawer').classList.remove('show')}
function openCart(){renderCart();show('drawer')}
$('#overlay').onclick=hideAll;$$('[data-close]').forEach(x=>x.onclick=hideAll);$('#openCart').onclick=openCart;$('#navCart').onclick=openCart;$('#floatingWA').onclick=()=>{if(totalUnits())openCart();else window.open('https://wa.me/','_blank')};
$('#search').oninput=e=>{filter.q=e.target.value;shown=48;render()};$('#searchBtn').onclick=()=>render();$('#sort').onchange=e=>{filter.sort=e.target.value;render()};$('#more').onclick=()=>{shown+=48;render()};
$$('[data-catalog]').forEach(x=>x.onclick=()=>{$$('[data-catalog]').forEach(y=>y.classList.remove('active'));x.classList.add('active');filter.catalog=x.dataset.catalog;shown=48;render()});
$$('[data-gender]').forEach(x=>x.onclick=()=>{$$('[data-gender]').forEach(y=>y.classList.remove('active'));x.classList.add('active');filter.gender=x.dataset.gender;shown=48;render()});
$('#navHome').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#navCats').onclick=()=>$('#catalogo').scrollIntoView({behavior:'smooth'});$('#navFav').onclick=()=>{filter.favorites=!filter.favorites;filter.q='';$('#search').value='';shown=48;render();$('#catalogo').scrollIntoView({behavior:'smooth'})};
function hero(){const picks=(window.ESENTIA_HERO_IDS||[]).map(id=>P.find(p=>p.id===id)).filter(Boolean);$('#heroProducts').innerHTML=picks.slice(0,3).map(p=>`<div class="heroProd"><img src="${imgSrc(p)}" alt="${p.name}"></div>`).join('')}
hero();updateBadge();render();
